apiVersion: apps/v1
kind: Deployment

metadata:
  name: pyhton-authservice
  namespace: python

spec:
  replicas: 2

  selector:
    matchLabels:
      name: auth
      expose: clusterIP

  template:
    metadata:
      labels:
        name: auth
        expose: clusterIP

    spec:
      containers:
        - name: authservice
          image: harishdoc098/proj:auth
          ports:
            - containerPort: 5001

          resources:
            requests:
              cpu: "40m"
              memory: "25Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
