apiVersion: apps/v1
kind: Deployment

metadata:
  name: pyhton-bookservice
  namespace: python

spec:
  replicas: 2

  selector:
    matchLabels:
      name: book
      expose: clusterIP

  template:
    metadata:
      labels:
        name: book
        expose: clusterIP

    spec:
      containers:
        - name: bookservice
          image: harishdoc098/proj:book
          ports:
            - containerPort: 5002

          resources:
            requests:
              cpu: "40m"
              memory: "25Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
