apiVersion: apps/v1
kind: Deployment

metadata:
  name: pyhton-borrowservice
  namespace: python

spec:
  replicas: 2

  selector:
    matchLabels:
      name: borrow
      expose: clusterIP

  template:
    metadata:
      labels:
        name: borrow
        expose: clusterIP

    spec:
      containers:
        - name: borrowservice
          image: harishdoc098/proj:borrow
          ports:
            - containerPort: 5003

          resources:
            requests:
              cpu: "40m"
              memory: "25Mi"
            limits:
              cpu: "100m"
              memory: "50Mi"
