apiVersion: v1
kind: PersistentVolume
metadata:
  name: python-volume       
spec:
  capacity:
    storage: 10Gi            
  accessModes:
    - ReadWriteOnce         
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""       
  csi:
    driver: ebs.csi.aws.com  
    volumeHandle: vol-09d2b86f27114e9cd  
    fsType: ext4             
