apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-volumeclaim
  namespace: python
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""       
  resources:
    requests:
      storage: 8Gi          
